spring:
  application:
    name: wallet-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/challenge_db}
    username: ${DB_USERNAME:challenge_user}
    password: ${DB_PASSWORD:challenge_password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration,classpath:db/seed

server:
  port: 8080

logging:
  level:
    com.challenge: INFO
